'use strict';
// FLEET FEED TESTS (WS5-FLEET-DATA) — the Fleet feed as a file.
// site/data/fleet.json is GENERATED by scripts/build_fleet_data.py from
// docs/ops/roam_policy_fixture.json. These tests pin the honesty contract:
//   - the feed's figures are a 1:1 verbatim join of the fixture rows (never
//     fabricated, never interpolated — a figure the fixture lacks stays null);
//   - provenance carries the fixture's measurement-window clause verbatim, and
//     an unwindowed feed must render every fee null;
//   - site/js/fleet.js is same-origin only and fails closed (fetch failure →
//     empty rows + {error:true}, never a fake zero);
//   - the builder is deterministic (run twice → byte-identical, no run-dependent
//     value inside books[]) and the payload stays <= 40KB.
const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const FEED_PATH = path.join(ROOT, 'site', 'data', 'fleet.json');
const FIXTURE_PATH = path.join(ROOT, 'docs', 'ops', 'roam_policy_fixture.json');
const FLEET_JS_PATH = path.join(ROOT, 'site', 'js', 'fleet.js');

const fleet = require('../site/js/fleet.js');

const TIER_BY_CLASS = { 'PAYS-LPS': 'PAYS', 'HOOK-MONETIZED': 'HOOK', DEAD: 'DEAD' };
const WINDOW_MARKER = 'window = ';

function readFeed() {
  return JSON.parse(fs.readFileSync(FEED_PATH, 'utf8'));
}

function readFixture() {
  return JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8'));
}

// The fixture's own measurement-window clause, located the same way the builder
// locates it (it is a semicolon-suffix of the swaps rule in the frozen fixture).
function fixtureWindowClause(fixture) {
  const rules = (fixture.meta && fixture.meta.extraction_rules) || [];
  for (const rule of rules) {
    const idx = rule.indexOf(WINDOW_MARKER);
    if (idx !== -1) return rule.slice(idx + WINDOW_MARKER.length).trim();
  }
  return null;
}

function sourceAprPct(row) {
  if (row.apr_m !== undefined && row.apr_m !== null) return row.apr_m;
  if (row.apr_f !== undefined && row.apr_f !== null) return row.apr_f;
  return null;
}

function expectedVol24h(row) {
  if (row.vol24h_source === 'meas-flow-day-05') return null; // flow figure, not volume
  return row.vol24h !== undefined && row.vol24h !== null ? row.vol24h : null;
}

function expectedPaysNothing(tier) {
  if (tier === 'HOOK') return true;   // fees flow to the hook — LP earns 0
  if (tier === 'PAYS') return false;  // charged fees reach LPs
  return null;                        // DEAD: no fee stream exists to route
}

test('feed parses; provenance pins the fixture source, a one-line method, an ISO date and the verbatim window clause', () => {
  const feed = readFeed();
  const fixture = readFixture();
  assert.strictEqual(feed.provenance.source, 'docs/ops/roam_policy_fixture.json');
  assert.ok(typeof feed.provenance.method === 'string' && feed.provenance.method.length > 0);
  assert.match(feed.provenance.generated, /^\d{4}-\d{2}-\d{2}$/);
  const clause = fixtureWindowClause(fixture);
  if (clause === null) {
    assert.strictEqual(feed.provenance.window, 'unwindowed — do not quote as current');
  } else {
    assert.strictEqual(feed.provenance.window, clause);
  }
});

test('summary counts equal the counts computed from books[]', () => {
  const feed = readFeed();
  const books = feed.books;
  let pays = 0, hook = 0, dead = 0;
  for (const b of books) {
    if (b.tier === 'PAYS') pays += 1;
    else if (b.tier === 'HOOK') hook += 1;
    else if (b.tier === 'DEAD') dead += 1;
  }
  assert.strictEqual(feed.summary.books, books.length);
  assert.strictEqual(feed.summary.paysLps, pays);
  assert.strictEqual(feed.summary.hookMonetized, hook);
  assert.strictEqual(feed.summary.dead, dead);
  assert.strictEqual(pays + hook + dead, books.length);
});

test('tier vocabulary is exactly {PAYS,HOOK,DEAD} and the per-tier census matches the fixture classes 1:1', () => {
  const feed = readFeed();
  const fixture = readFixture();
  const byPool = new Map(feed.books.map((b) => [b.poolId, b]));
  assert.strictEqual(feed.books.length, fixture.books.length);
  let pays = 0, hook = 0, dead = 0;
  for (const row of fixture.books) {
    const book = byPool.get(row.poolId);
    assert.ok(book, 'fixture row missing from feed: ' + row.poolId);
    const expected = TIER_BY_CLASS[row['class']];
    assert.ok(expected, 'fixture carries an unmapped class: ' + row['class']);
    assert.strictEqual(book.tier, expected);
    if (expected === 'PAYS') pays += 1;
    else if (expected === 'HOOK') hook += 1;
    else dead += 1;
  }
  assert.strictEqual(feed.summary.paysLps, pays);
  assert.strictEqual(feed.summary.hookMonetized, hook);
  assert.strictEqual(feed.summary.dead, dead);
});

test('window rule: a windowed feed carries measured fees; an unwindowed feed would force every fee null', () => {
  const feed = readFeed();
  const win = feed.provenance.window;
  const windowed = typeof win === 'string' && win.length > 0 && !win.startsWith('unwindowed');
  if (!windowed) {
    for (const b of feed.books) assert.strictEqual(b.feeAprPct, null, 'unwindowed feed must not quote fees');
    return;
  }
  const withFee = feed.books.filter((b) => b.feeAprPct !== null);
  assert.ok(withFee.length > 0, 'windowed feed with zero fee figures does not match the fixture coverage');
});

test('no fabrication: every pinned field of every book is the verbatim 1:1 join of its fixture row', () => {
  const feed = readFeed();
  const fixture = readFixture();
  const byPool = new Map();
  for (const b of feed.books) {
    assert.match(b.poolId, /^0x[0-9a-f]{64}$/, 'poolId is not the fixture verbatim 64-hex id');
    assert.strictEqual(byPool.has(b.poolId), false, 'duplicate poolId in feed');
    byPool.set(b.poolId, b);
  }
  assert.strictEqual(feed.books.length, fixture.books.length);
  for (const row of fixture.books) {
    const b = byPool.get(row.poolId);
    assert.ok(b, 'feed missing fixture row ' + row.poolId);
    assert.strictEqual(b.pair, row.book);
    assert.strictEqual(b.tier, TIER_BY_CLASS[row['class']]);
    assert.strictEqual(b.feeAprPct, sourceAprPct(row));
    assert.strictEqual(b.tvlUsd, row.tvl !== undefined && row.tvl !== null ? row.tvl : null);
    assert.strictEqual(b.vol24hUsd, expectedVol24h(row));
    assert.strictEqual(b.chargedFeeBps, row.fee_wavg !== undefined && row.fee_wavg !== null ? row.fee_wavg : null);
    assert.strictEqual(b.paysNothingToLps, expectedPaysNothing(TIER_BY_CLASS[row['class']]));
    assert.ok(typeof b.note === 'string' && b.note.length > 0);
  }
});

test('null-fee honesty: books without a source APR stay null; flow-only rows never render volume as a volume figure', () => {
  const feed = readFeed();
  const fixture = readFixture();
  const nullAprFixture = new Set(
    fixture.books.filter((r) => sourceAprPct(r) === null).map((r) => r.poolId)
  );
  const nullAprFeed = new Set(feed.books.filter((b) => b.feeAprPct === null).map((b) => b.poolId));
  assert.deepStrictEqual([...nullAprFeed].sort(), [...nullAprFixture].sort());
  for (const row of fixture.books) {
    if (row.vol24h_source === 'meas-flow-day-05') {
      const b = feed.books.find((x) => x.poolId === row.poolId);
      assert.strictEqual(b.vol24hUsd, null, 'measured $/day flow must not be rendered as vol24hUsd');
      assert.ok(/measured \$\/day flow, not volume/.test(b.note));
    }
  }
  for (const b of feed.books) {
    if (b.tier === 'DEAD') {
      assert.strictEqual(b.chargedFeeBps, null, 'zero-swap books are never estimated');
      assert.strictEqual(b.feeAprPct, null);
    }
    if (b.tier === 'HOOK') {
      assert.strictEqual(b.paysNothingToLps, true);
      assert.ok(b.note.indexOf('fees flow to the hook — LP earns 0') !== -1);
    }
  }
});

test('fmtPct/fmtUsd: null/non-number render the unavailable glyph; a measured 0 renders as a real zero', () => {
  assert.strictEqual(fleet.fmtPct(null), '—');
  assert.strictEqual(fleet.fmtPct(undefined), '—');
  assert.strictEqual(fleet.fmtPct(NaN), '—');
  assert.strictEqual(fleet.fmtPct(0), '0.0%');
  assert.strictEqual(fleet.fmtPct(12.34), '12.3%');
  assert.strictEqual(fleet.fmtPct(447), '447.0%');
  assert.strictEqual(fleet.fmtPct(-3.21), '-3.2%');
  assert.strictEqual(fleet.fmtUsd(null), '—');
  assert.strictEqual(fleet.fmtUsd(undefined), '—');
  assert.strictEqual(fleet.fmtUsd(0), '$0');
  assert.strictEqual(fleet.fmtUsd(999), '$999');
  assert.strictEqual(fleet.fmtUsd(16000), '$16.0K');
  assert.strictEqual(fleet.fmtUsd(466721), '$466.7K');
  assert.strictEqual(fleet.fmtUsd(35605482), '$35.6M');
  assert.strictEqual(fleet.fmtUsd(7224187), '$7.2M');
  assert.strictEqual(fleet.unavailable, '—');
});

test('same-origin only: the module carries no origin-scheme string and fetches the feed on a relative path', async () => {
  const src = fs.readFileSync(FLEET_JS_PATH, 'utf8');
  assert.strictEqual(src.indexOf('http://'), -1, 'fleet.js must not reference an absolute origin');
  assert.strictEqual(src.indexOf('https://'), -1, 'fleet.js must not reference an absolute origin');
  assert.ok(src.indexOf("var FEED_URL = './data/fleet.json'") !== -1, 'feed path must stay relative');

  let fetchedUrl = null;
  const originalFetch = globalThis.fetch;
  globalThis.fetch = function (url) {
    fetchedUrl = url;
    return Promise.resolve({
      ok: true,
      json: function () { return Promise.resolve(readFeed()); }
    });
  };
  try {
    await new Promise((resolve) => fleet.load(() => resolve()));
    assert.strictEqual(fetchedUrl, './data/fleet.json');
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('fail-closed: fetch failure, non-ok response and invalid payload all yield {error:true}, empty rows and null summary; a good load recovers', async () => {
  const originalFetch = globalThis.fetch;
  const scenarios = [
    function () { return Promise.reject(new Error('network down')); },
    function () { return Promise.resolve({ ok: false, json: function () { return Promise.resolve({}); } }); },
    function () { return Promise.resolve({ ok: true, json: function () { return Promise.resolve({ books: 'garbage' }); } }); }
  ];
  try {
    for (const scenario of scenarios) {
      globalThis.fetch = scenario;
      const received = await new Promise((resolve) => fleet.load(resolve));
      assert.deepStrictEqual(received, { error: true });
      assert.deepStrictEqual(fleet.rows(), []);
      assert.deepStrictEqual(fleet.rows('HOOK'), []);
      assert.strictEqual(fleet.summary(), null);
    }
    // recovery: a good load after failures restores real data
    globalThis.fetch = function () {
      return Promise.resolve({ ok: true, json: function () { return Promise.resolve(readFeed()); } });
    };
    const feed = await new Promise((resolve) => fleet.load(resolve));
    assert.strictEqual(feed.error, undefined);
    assert.ok(fleet.rows().length > 0);
    assert.ok(fleet.summary().books > 0);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('rows(): HOOK books render first-class, unknown tiers fail closed to [], null fees sort last within a tier', async () => {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = function () {
    return Promise.resolve({ ok: true, json: function () { return Promise.resolve(readFeed()); } });
  };
  try {
    await new Promise((resolve) => fleet.load(resolve));
    const all = fleet.rows();
    const rank = { HOOK: 0, PAYS: 1, DEAD: 2 };
    let lastRank = -1;
    const nullSeen = {};
    const lastFeeSeen = {};
    for (const b of all) {
      const r = rank[b.tier];
      assert.ok(r >= lastRank, 'tier order must be HOOK → PAYS → DEAD');
      lastRank = r;
      if (b.feeAprPct === null) {
        nullSeen[b.tier] = true;
      } else {
        assert.ok(!nullSeen[b.tier], 'within a tier, null fees sort last — never before a measured figure');
        if (lastFeeSeen[b.tier] !== undefined) {
          assert.ok(b.feeAprPct <= lastFeeSeen[b.tier], 'within a tier, measured fees sort descending');
        }
        lastFeeSeen[b.tier] = b.feeAprPct;
      }
    }
    const hooks = fleet.rows('HOOK');
    assert.ok(hooks.length > 0);
    for (const b of hooks) assert.strictEqual(b.tier, 'HOOK');
    assert.deepStrictEqual(fleet.rows('NOT-A-TIER'), []);
    const pays = fleet.rows('PAYS');
    assert.strictEqual(pays[pays.length - 1].feeAprPct, null, 'the one source-less APR sorts last');
  } finally {
    globalThis.fetch = originalFetch;
  }
});

test('determinism: the builder run twice is byte-identical, "generated" appears only in provenance, and the payload stays <= 40KB', () => {
  execFileSync('python3', ['scripts/build_fleet_data.py'], { cwd: ROOT, stdio: 'pipe' });
  const first = fs.readFileSync(FEED_PATH);
  execFileSync('python3', ['scripts/build_fleet_data.py'], { cwd: ROOT, stdio: 'pipe' });
  const second = fs.readFileSync(FEED_PATH);
  assert.ok(first.equals(second), 'builder re-run must be byte-stable');

  const raw = second.toString('utf8');
  assert.strictEqual(raw.split('"generated"').length - 1, 1, '"generated" is a provenance-only field');
  const feed = JSON.parse(raw);
  for (const b of feed.books) {
    assert.strictEqual('generated' in b, false, 'no run-dependent values inside books[]');
    assert.strictEqual('timestamp' in b, false);
  }
  const size = fs.statSync(FEED_PATH).size;
  assert.ok(size <= 40960, 'payload ' + size + ' bytes exceeds the 40KB gate');
});

// ── WS5-OURS (2026-09-07) — the OURS-badge mechanism ───────────────────────
// The badge is data-driven: build_fleet_data.py's OURS map is the ONLY source,
// empty today because $WELL is not deployed. The day the capital exists (launch
// day: the pair's graduated poolId + the POL roamer books as S1 seeds them),
// the feed carries it and the page badges it — with the same measured window
// labels as every other figure. These pins keep that promise honest:
// (1) shape: every book carries the `ours` key (null or {pair,status,...});
//     statuses are the closed vocabulary; summary.ours is the census.
// (2) TODAY: the census is ZERO — no badge may pre-exist the capital.
// (3) the accessor fails closed and is per-book.
// (4) teeth: a phantom poolId or an unknown status ABORTS the builder (executed
//     against source-patched copies with ROOT pinned to this repo — the guards
//     fire before any write, so the real feed is never at risk).
const OURS_STATUSES = ['LIVE', 'SEEDED', 'WINDING-DOWN'];

test('WS5-OURS: every book carries the ours key; status vocabulary closed; census matches; today the census is zero', () => {
  const feed = readFeed();
  assert.ok('ours' in feed.summary, 'summary carries the ours census');
  for (const b of feed.books) {
    assert.ok('ours' in b, 'book ' + b.pair + ' must carry an ours key (null, never absent)');
    if (b.ours !== null) {
      assert.strictEqual(typeof b.ours.status, 'string', 'ours.status is a string');
      assert.ok(OURS_STATUSES.includes(b.ours.status), 'ours.status ' + b.ours.status + ' outside the closed vocabulary');
      assert.strictEqual(typeof b.ours.pair, 'string', 'ours.pair is a string');
    }
  }
  const count = feed.books.filter((b) => b.ours !== null).length;
  assert.strictEqual(feed.summary.ours, count, 'summary.ours must equal the tagged-book census');
  assert.strictEqual(feed.summary.ours, 0, 'today: $WELL is not deployed — no OURS badge may pre-exist the capital');
});

test('WS5-OURS: fleet.isOurs fails closed pre-load and per-book after', async () => {
  delete require.cache[require.resolve('../site/js/fleet.js')];
  const fresh = require('../site/js/fleet.js');
  assert.strictEqual(fresh.isOurs({ poolId: 'anything' }), null, 'isOurs is null before any load');
  assert.strictEqual(fresh.isOurs(null), null);

  const originalFetch = globalThis.fetch;
  const feed = JSON.parse(JSON.stringify(readFeed()));
  feed.books[0].ours = { pair: feed.books[0].pair, status: 'LIVE', note: 'injected for the accessor test' };
  feed.summary.ours = 1; // keep the injected feed self-consistent (validate() enforces the census)
  globalThis.fetch = function () {
    return Promise.resolve({ ok: true, json: function () { return Promise.resolve(feed); } });
  };
  try {
    await new Promise((resolve) => fresh.load(resolve));
    assert.strictEqual(fresh.isOurs(feed.books[0]), 'LIVE', 'tagged book returns its status');
    assert.strictEqual(fresh.isOurs(feed.books[1]), null, 'untagged book is not ours');
    assert.strictEqual(fresh.summary().ours, 1);
  } finally {
    globalThis.fetch = originalFetch;
  }
});

function runPatchedBuilder(mutate) {
  const src = fs.readFileSync(path.join(ROOT, 'scripts', 'build_fleet_data.py'), 'utf8');
  const patched = mutate(src).replace(
    'ROOT = Path(__file__).resolve().parents[1]',
    "ROOT = Path(r'" + ROOT + "')"
  );
  const tmp = path.join(require('node:os').tmpdir(), 'ws5_ours_teeth_' + (mutate.name || 'anon') + '.py');
  fs.writeFileSync(tmp, patched);
  try {
    execFileSync('python3', [tmp], { cwd: ROOT, stdio: 'pipe' });
    return { code: 0, err: '' };
  } catch (e) {
    return { code: e.status === undefined ? -1 : e.status, err: String(e.stderr || e) };
  }
}

test('WS5-OURS teeth: a phantom poolId ABORTS the builder (never a badge on a book the feed does not carry)', () => {
  const fake = "'0x" + 'ab'.repeat(32) + "'";
  const r = runPatchedBuilder(function injectPhantom(src) {
    return src.replace("OURS = {\n", "OURS = { " + fake + ": { 'pair': 'PHANTOM/ETH', 'status': 'LIVE' } } if True else {\n");
  });
  assert.notStrictEqual(r.code, 0, 'builder must exit non-zero on a phantom OURS entry');
  assert.ok(/phantom/i.test(r.err), 'the failure must name the phantom guard, got: ' + r.err.slice(0, 200));
});

test('WS5-OURS teeth: an unknown OURS status ABORTS the builder', () => {
  const realId = readFeed().books[0].poolId;
  const r = runPatchedBuilder(function injectBadStatus(src) {
    return src.replace("OURS = {\n", "OURS = { '" + realId + "': { 'pair': 'X/Y', 'status': 'GUARANTEED' } } if True else {\n");
  });
  assert.notStrictEqual(r.code, 0, 'builder must exit non-zero on a bad status');
  assert.ok(/status/i.test(r.err), 'the failure must name the status guard, got: ' + r.err.slice(0, 200));
});
